# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

services:
    app.admin.party:
        class: BackBundle\Admin\PartyAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Party Gestion", label: "Party"}
        arguments:
            - ~
            - BackBundle\Entity\Party
            - ~

    app.admin.reservation:
        class: BackBundle\Admin\ReservationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Reservation Gestion", label: "Reservation" }
        arguments:
            - ~
            - BackBundle\Entity\Reservation
            - ~

    app.admin.mail:
        class: BackBundle\Admin\MailAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Mails List", label: "Mail" }
        arguments:
            - ~
            - BackBundle\Entity\Mail
            - ~