<?php

namespace AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReservationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationsRepository extends EntityRepository
{
}
